language: ruby
rvm:
- 2.5.1
before_script:
- bundle exec rake db:create --all
- bundle exec rake db:migrate
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
deploy:
  api_key:
    secure: Jpdl0bAhEJkTHWzMStyJUULBWMWghRtOfb7ZP5BOqBs1tgPW9XaJtbIEOf475UhHNUJ9Wvq/FCQ9PpZtOGRa3SRvc2+XnT8uBI1w10yPeuip+aXYUE37X8KRxE9t2XkxGggxbyjgjHQ7K3NzKPXsNVt2xOe62glGWXhyVuZ5aiMO2H5VNuGMrvGpthTvWuwRD58iNqQyoKl+HDMlY/7tut5SbaYrfUUmHK1Gd/3DE2IlBauGBsphbJDGgf5mIwODKHvF9msgfYBn8z0Uys0SGOdEoTL54NnGqH5+ApvEJNfpAnRfgQNNALz/eQ2SYOh0erFjwT8tyaYlQ7zlDAzZ4Bo/th0GBGNpNuO1qE1tiopxTJrwAxyGFS6r1i/6VjCgQOHmYQQbldS/+qd2vTmGXYDzLjIt09PHcd0IY8WBa2GGtzM1jwF8t2WfWzDPM5e8sWLZ1L0WZkVwdP7LVjKIqJ2tv/hm9IMMMsezK2PPp+cG32qUqkVFg5MThA5h5Dk6g7iFdd9ALSOLXvkDXPwjYMxV3+FVWO9QMUQmXpSrlDMXCrTNekwfxnB4mukVjAIZA5T1uoxZc7FhGSPYTOxHxoITUXeyBfOtZeGY3ZznaIlmrUFKSNM/fcr6pHF5fJJgRohFbXCiSr5eTgNZN0lnbAjr1xI2b+QcIrBPoLPt2pI=
